[build]
  base = "apps/client"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://powerful-ridge-88886.herokuapp.com/api/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
